// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type SuggestRequest struct {
	Keyword string `form:"keyword"`
}

type SuggestResponse struct {
	RelatedWords []*Keyword `json:"related_words"`
}

type Keyword struct {
	Content string `json:"content"`
}
